services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    env_file:
      - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres
    environment:
      # - POSTGRES_PASSWORD=temp
      - POSTGRES_DB=musicPracticeCompanion
    volumes:
      - postgres-db:/var/lib/postgresql

volumes:
  postgres-db:

