name: CI/CD Pipeline with GitHub
on: [push]
jobs:
  Build:
    environment:
      name: testing
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{secrets.DATABASE_USERNAME}}
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v4
      - name: Setting up python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
          cache: "pip"
          cache-dependency-path: api/requirements.txt
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install requirements
        run: pip install -r api/requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest -v -s

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v3
#ONCE I GET CI/CD PIPELINE TO WORK WITH NO ISSUE I WILL ADD DOCKER ONLY DEPLOYMENT
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./api
      #     file: ./api/Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backendapi:latest
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    environment:
      name: production
    steps:
      - name: Write SSH key
        run: |
          echo "${{ secrets.PROD_SSH_KEY_B64 }}" | base64 -d > key.pem
          chmod 600 key.pem
      - name: Deploy to EC2 over SSH (pull & restart container)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key_path: key.pem
          script: |
            whoami
            hostname
            uptime
            set -e
            cd /home/ubuntu/Music_Practice_Companion/src
            git fetch --all
            git reset --hard origin/main

            sudo systemctl daemon-reload
            sudo systemctl restart api
            sudo systemctl status api --no-pager -l